name: Articles Update Tracker

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send notification
        shell: pwsh
        env:
          COMMITS: ${{ toJSON(github.event.commits) }}
          AUTHOR: ${{ github.event.pusher.name }}
          GOOGLE_CHAT_HOOK: ${{ secrets.VEGAIT_BETA_GOOGLE_CHAT }}
          VISIT_URL: ${{ vars.PAGES_URL }}
        run: |
          ./.notifications/notify.ps1
